export const worksData = [
  // デザイン
  {
    id: 1, category: 'デザイン',
    title: '7つの謎と願い叶える展覧会',
    description: 'メインビジュアルを制作しました',
    image: '/image/negakana.png',
    detail: 'メインビジュアル',
  },
  {
    id: 2, category: 'デザイン',
    title: '今宵、幽幻なる孤城で魔女は嗤う',
    description: '広報チラシ制作',
    image: '/image/yugen.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 3, category: 'デザイン',
    title: 'ゴクアクラボからの生還',
    description: 'イラスト制作',
    image: '/image/gokuakurabo.webp',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 4, category: 'デザイン',
    title: 'ペーパーテスト',
    description: 'イラスト制作',
    image: '/image/papertest.webp',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 5, category: 'デザイン',
    title: 'スゴロククエストクエスチョン',
    description: 'イラスト制作',
    image: '/image/sugorokukuesutokuesutyon.webp',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 6, category: 'デザイン',
    title: '吉祥寺謎解き追憶のアルバム',
    description: 'イラスト制作',
    image: '/image/kichijojikioku.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 7, category: 'デザイン',
    title: 'なつのななつの宝物',
    description: 'イラスト制作',
    image: '/image/natunonanatuno.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 8, category: 'デザイン',
    title: 'メトロタイムゲート',
    description: 'イラスト制作',
    image: '/image/metrotimegate.jpeg',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 9, category: 'デザイン',
    title: '99g',
    description: 'イラスト制作',
    image: '/image/tsukumogram.webp',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 10, category: 'デザイン',
    title: '年越しハック',
    description: 'イラスト制作',
    image: '/image/tosikosihack.JPG',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 11, category: 'デザイン',
    title: '或る病室のキュウメイ前夜',
    description: 'イラスト制作',
    image: '/image/kyumei.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 12, category: 'デザイン',
    title: 'アケロナイスビンゴ',
    description: 'イラスト制作',
    image: '/image/anabingo.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 13, category: 'デザイン',
    title: 'ハイドアンドシーク',
    description: 'イラスト制作',
    image: '/image/recordsi.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 14, category: 'デザイン',
    title: 'BR34K 53COND',
    description: 'イラスト制作',
    image: '/image/breaksecond.jpg',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 14, category: 'デザイン',
    title: 'ラッキー謎みくじ',
    description: 'イラスト制作',
    image: '/image/recordra.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 15, category: 'デザイン',
    title: 'ファイトフォーライフ',
    description: 'イラスト制作',
    image: '/image/recordfa.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 16, category: 'デザイン',
    title: 'ワンサカード',
    description: 'イラスト制作',
    image: '/image/wansacard.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 17, category: 'デザイン',
    title: 'リサイコロボックスプラス',
    description: 'イラスト制作',
    image: '/image/recycle_plus.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 18, category: 'デザイン',
    title: 'ナゾトレ',
    description: 'イラスト制作',
    image: '/image/nazotore.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 19, category: 'デザイン',
    title: '兜町探偵局有料版',
    description: 'イラスト制作',
    image: '/image/kabutotyo2.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 20, category: 'デザイン',
    title: '兜町探偵局無料版',
    description: 'イラスト制作',
    image: '/image/kabutotyo.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 21, category: 'デザイン',
    title: 'リリリィンカーテンコール',
    description: 'イラスト制作',
    image: '/image/ririri.jpeg',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 22, category: 'デザイン',
    title: 'KAGIREAL',
    description: 'イラスト制作',
    image: '/image/kagireal.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 23, category: 'デザイン',
    title: 'PreparePresents',
    description: 'イラスト制作',
    image: '/image/PreparePresents.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
  {
    id: 17, category: 'デザイン',
    title: 'DeTESTive',
    description: 'イラスト制作',
    image: '/image/DeTESTive.png',
    detail: '大学のイベントで配布されたチラシです。',
  },
];