export const worksData = [
  // デザイン
  {
    id: 1,
    title: '7つの謎と願い叶える展覧会',
    description: 'AnotherVision五月祭企画\n物販会場で手軽に遊べる謎解きコンテンツを開催。',
    image: '/image/negakana.png',
    detail: '構成とメインビジュアルを制作しました。',
    link: 'https://anothervision.tokyo/contents/details/negakana',
  },
  {
    id: 2,
    title: '今宵、幽幻なる孤城で魔女は嗤う',
    description: '迎えるのは終宴か / 迎えるのは終焉か\nAnotherVision -unlimited- 公演。',
    image: '/image/yugen.png',
    detail: '構成と謎制作とデザインをしました。',
    link: 'https://anothervision.tokyo/contents/details/yugen',
  },
  {
    id: 3,
    title: 'ペーパーテスト',
    description: 'これから試験を開始します。\n1. 試験用紙は丁寧に扱うこと\n2. 分からないことがある場合は試験官に聞くこと\n3. 試験中はみんなで情報共有と役割分担をしてください',
    image: '/image/papertest.jpeg',
    detail: '制作指揮をしました。',
    link: 'https://tsukumorozuya.com/create/papertest',
  },
  {
    id: 4,
    title: 'ゴクアクラボからの生還',
    description: '待ち受けるのは、予測不能の妨害。',
    image: '/image/gokuakurabo.webp',
    detail: '構成と謎制作をしました。',
    link: 'https://tumbleweed.jp/event/gokuaku-labo',
  },
  {
    id: 5,
    title: 'スゴロククエストクエスチョン',
    description: 'サイコロとその頭脳で、世界を変えろ。',
    image: '/image/sugoroku.jpeg',
    detail: '謎制作をしました。',
    link: 'https://tsukumorozuya.com/create/sugoroku',
  },
  {
    id: 6,
    title: '吉祥寺謎解き追憶のアルバム',
    description: '吉祥寺謎解き街歩き',
    image: '/image/kichijojikioku.png',
    detail: 'LPサイトを制作しました。',
    link: 'https://machihack.com/kichijoji?_gl=1*1ts86ra*_gcl_au*NDczMTc3MzE4LjE3NDkzNzY2Nzk.',
  },
  {
    id: 7,
    title: 'なつのななつの宝物',
    description: '夏休み限定web企画',
    image: '/image/natunonanatuno.png',
    detail: 'ゲームサイトを制作しました。',
    link: 'https://www.machihack.com/events/0abddb82-8d73-462c-ac96-439b69b4d2c0',
  },
  {
    id: 8,
    title: 'メトロタイムゲート',
    description: '謎解き×地下鉄×街歩き',
    image: '/image/metrotimegate.jpeg',
    detail: 'お試し謎を制作しました。',
    link: 'https://tokyometro.machihack.com/?_gl=1*1ts86ra*_gcl_au*NDczMTc3MzE4LjE3NDkzNzY2Nzk.',
  },
  {
    id: 9,
    title: '99g',
    description: '99gと表示してください。',
    image: '/image/tsukumoguramu.jpeg',
    detail: '制作指揮をしました。',
    link: 'https://tsukumorozuya.com/create/99g',
  },
  {
    id: 10,
    title: '年越しハック',
    description: '冬休み限定web謎解き企画',
    image: '/image/tosikosihack.JPG',
    detail: '謎制作をしました。',
  },
  {
    id: 11,
    title: '或る病室のキュウメイ前夜',
    description: 'AnotherVision五月祭企画第9弾。\nあなたへうつるは この想い',
    image: '/image/kyumei.png',
    detail: '構成と謎とデザイン制作をしました。',
    link: 'https://anothervision.tokyo/contents/details/kyumei',
  },
  {
    id: 12,
    title: 'アケロナイスビンゴ',
    description: 'ひらけ！ ひらめけ！ ナイスビンゴ！',
    image: '/image/anabingo.png',
    detail: '構成と謎とメインビジュアルを制作しました。',
    link: 'https://anothervision.tokyo/contents/details/anabingo',
  },
  {
    id: 13,
    title: 'ハイドアンドシーク',
    description: '会場内にあるガーランドの中から隠れたおばけを探し出せ！',
    image: '/image/recordsi.png',
    detail: '制作指揮をしてメインビジュアルを制作しました。',
  },
  {
    id: 14,
    title: 'BR34K 53COND',
    description: '目標タイム：3秒以内にクリア',
    image: '/image/breaksecond.jpg',
    detail: '謎制作をしました。',
  },
  {
    id: 15,
    title: 'ラッキー謎みくじ',
    description: '謎×おみくじ\n謎を解いて運試しをしてみよう',
    image: '/image/recordra.png',
    detail: 'デザインを制作しました。',
  },
  {
    id: 16,
    title: 'ファイトフォーライフ',
    description: '謎を解いて生き延びよう',
    image: '/image/recordfa.png',
    detail: '構成を制作しました。',
  },
  {
    id: 17,
    title: 'ワンサカード',
    description: 'ひらめかなくても、運さえあれば？',
    image: '/image/wansacard.png',
    detail: 'デザインを制作しました。',
    link: 'https://anothervision.tokyo/contents/details/wansacard',
  },
  {
    id: 18,
    title: 'リサイコロボックスプラス',
    description: 'リサイコロボックスのアップデートが完了しました。',
    image: '/image/recycle_plus.png',
    detail: '構成と謎を制作しました。',
    link: 'https://anothervision.tokyo/contents/details/recycle_plus',
  },
  {
    id: 19,
    title: '東大ナゾトレ',
    description: 'フジテレビ番組今夜はナゾトレの東大謎トレのコーナー',
    image: '/image/nazotore.jpg',
    detail: '謎を制作しています。',
    link: 'https://www.fujitv.co.jp/nazotore/',
  },
  {
    id: 20,
    title: '兜町探偵局有料版',
    description: '日本橋兜町で起きた事件を解決せよ',
    image: '/image/kabutotyo2.png',
    detail: 'お試し謎を制作しました。',
    link: 'https://machihack.com/kabutocho-detective?_gl=1*1xqabyy*_gcl_au*NDczMTc3MzE4LjE3NDkzNzY2Nzk.',
  },
  {
    id: 21,
    title: '兜町探偵局無料版',
    description: '日本橋兜町で起きた事件を解決せよ',
    image: '/image/kabutotyo.png',
    detail: 'お試し謎を制作しました。',
  },
  {
    id: 22,
    title: 'リリリィンカーテンコール',
    description: '──これは、“謎のあるイマーシブ“。\n散りばめられたヒントを繋ぎ、真相に辿り着けるか。\n《 話し、閃き、動き出す、あなただけの物語。》',
    image: '/image/ririri.jpeg',
    detail: 'デザインを制作しました。',
    link: 'https://espact.net/rerere/',
  },
  {
    id: 23,
    title: 'KAGIREAL',
    description: 'AR宝探し',
    image: '/image/kagireal.png',
    detail: '構成と謎を制作しました。',
  },
  {
    id: 24,
    title: 'PreparePresents',
    description: '駒場祭謎解き公演第9弾\n今宵のクリスマスは、すべてあなたたちに託されたー',
    image: '/image/PreparePresents.png',
    detail: '構成と謎とデザインを制作しました。',
    ink: 'https://anothervision.tokyo/contents/details/PreparePresents',
  },
  {
    id: 25,
    title: 'DeTESTive',
    description: '23年度駒場祭持ち帰り謎！',
    image: '/image/DeTESTive.png',
    detail: 'デザインを制作しました。',
    link: 'https://anothervision.tokyo/contents/details/DeTESTive',
  },
];